theme: jekyll-theme-cayman
title: Learn Catalan Today
description: Simple steps to perfect Catalan
github:
  page2: About Catalonia.html
  page3: The History of Catalonia.html
  page4: Catalan Vocabulary.html
  page5: Catalan Phrases.html
  page6: Notable Catalan Artists.html
  page7: Further study.html
